//! Active-Record-style models — Elyra's Eloquent, thin over sqlx.
//!
//! `#[derive(Model)]` generates CRUD (`all` / `find` / `insert` / `update` /
//! `delete` / `save`) plus a small typed [`Query`] builder. It's a thin layer
//! over the `Database` pool we already have — not a second ORM engine.
//!
//! Placeholders are rendered per driver (`?` for sqlite/mysql, `$n` for
//! postgres) since the sqlx `Any` driver doesn't translate them; inserts use
//! `RETURNING` on sqlite/postgres and `last_insert_id()` on MySQL.
//!
//! v1 assumptions (documented, may loosen later): the primary key is an
//! `i64` autoincrement column (a value of `0` means "unsaved"), and column names
//! equal field names.

use std::collections::HashMap;
use std::marker::PhantomData;

use sqlx::any::{AnyArguments, AnyRow};
use sqlx::{Arguments, Row};

use crate::error::{Error, Result};
use crate::{Database, Driver};

/// Metadata a `#[derive(Model)]` type provides, used by the [`Query`] builder.
pub trait Model: Sized + Send + Unpin {
    const TABLE: &'static str;
    const PK: &'static str;
    const COLUMNS: &'static [&'static str];
    /// The soft-delete column, when the model declares `#[model(soft_deletes)]`.
    /// Queries then exclude trashed rows unless asked not to.
    const SOFT_DELETE: Option<&'static str> = None;

    /// Map a row into `Self`. Generated by the derive.
    fn from_row(row: &AnyRow) -> Result<Self>;

    /// Read an `i64`-valued column from this instance by name (used by eager
    /// loading to collect keys / group results). Generated by the derive;
    /// returns `None` for non-integer columns.
    fn get_i64(&self, column: &str) -> Option<i64>;
}

/// Eager-load a `has_many` relation for a batch of parents: one `WHERE fk IN
/// (..)` query, grouped by foreign key. Returns a map keyed by parent PK value.
pub async fn eager_has_many<P: Model, C: Model>(
    db: &Database,
    parents: &[P],
    parent_pk: &str,
    foreign_key: &str,
) -> Result<HashMap<i64, Vec<C>>> {
    let ids: Vec<i64> = parents
        .iter()
        .filter_map(|p| p.get_i64(parent_pk))
        .collect();
    let mut grouped: HashMap<i64, Vec<C>> = HashMap::new();
    if ids.is_empty() {
        return Ok(grouped);
    }
    let children = Query::<C>::new().where_in(foreign_key, ids).get(db).await?;
    for child in children {
        if let Some(key) = child.get_i64(foreign_key) {
            grouped.entry(key).or_default().push(child);
        }
    }
    Ok(grouped)
}

/// Eager-load a `has_one` relation (the first child per parent key).
pub async fn eager_has_one<P: Model, C: Model>(
    db: &Database,
    parents: &[P],
    parent_pk: &str,
    foreign_key: &str,
) -> Result<HashMap<i64, C>> {
    let grouped = eager_has_many::<P, C>(db, parents, parent_pk, foreign_key).await?;
    Ok(grouped
        .into_iter()
        .filter_map(|(key, children)| children.into_iter().next().map(|c| (key, c)))
        .collect())
}

/// Eager-load a `belongs_to` relation for a batch of children: query the parents
/// whose PK is in the children's foreign keys. Returns a map keyed by parent PK,
/// so the caller can look up `map[&child.fk]`.
pub async fn eager_belongs_to<C: Model, P: Model>(
    db: &Database,
    children: &[C],
    foreign_key: &str,
    parent_pk: &str,
) -> Result<HashMap<i64, P>> {
    let ids: Vec<i64> = children
        .iter()
        .filter_map(|c| c.get_i64(foreign_key))
        .collect();
    let mut by_id: HashMap<i64, P> = HashMap::new();
    if ids.is_empty() {
        return Ok(by_id);
    }
    let parents = Query::<P>::new().where_in(parent_pk, ids).get(db).await?;
    for parent in parents {
        if let Some(key) = parent.get_i64(parent_pk) {
            by_id.insert(key, parent);
        }
    }
    Ok(by_id)
}

/// Render the placeholder for bind position `index` (1-based) on `driver`.
pub fn placeholder(driver: Driver, index: usize) -> String {
    match driver {
        Driver::Postgres => format!("${index}"),
        _ => "?".to_string(),
    }
}

/// Render `count` comma-separated placeholders starting at position 1.
pub fn placeholders(driver: Driver, count: usize) -> String {
    (1..=count)
        .map(|i| placeholder(driver, i))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Reject anything that isn't a bare SQL identifier (columns can't be bound).
fn valid_ident(ident: &str) -> bool {
    !ident.is_empty() && ident.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// Like [`valid_ident`], but allows one `table.column` qualifier — needed by
/// joins, and by `where`/`order` clauses that disambiguate a joined column.
fn valid_qualified_ident(ident: &str) -> bool {
    let mut parts = ident.split('.');
    let ok = match (parts.next(), parts.next()) {
        (Some(a), None) => valid_ident(a),
        (Some(a), Some(b)) => valid_ident(a) && valid_ident(b),
        _ => false,
    };
    ok && parts.next().is_none()
}

/// A bindable scalar for the query builder.
#[derive(Clone, Debug)]
pub enum Value {
    Int(i64),
    Real(f64),
    Text(String),
    Bool(bool),
    Null,
}

impl From<i64> for Value {
    fn from(v: i64) -> Self {
        Value::Int(v)
    }
}
impl From<i32> for Value {
    fn from(v: i32) -> Self {
        Value::Int(v as i64)
    }
}
impl From<bool> for Value {
    fn from(v: bool) -> Self {
        Value::Bool(v)
    }
}
impl From<f64> for Value {
    fn from(v: f64) -> Self {
        Value::Real(v)
    }
}
impl From<&str> for Value {
    fn from(v: &str) -> Self {
        Value::Text(v.to_owned())
    }
}
impl From<String> for Value {
    fn from(v: String) -> Self {
        Value::Text(v)
    }
}

#[derive(Clone, Copy)]
enum Op {
    Eq,
    Ne,
    Lt,
    Gt,
    Le,
    Ge,
}

impl Op {
    fn sql(self) -> &'static str {
        match self {
            Op::Eq => "=",
            Op::Ne => "<>",
            Op::Lt => "<",
            Op::Gt => ">",
            Op::Le => "<=",
            Op::Ge => ">=",
        }
    }
}

enum Clause {
    Cmp(String, Op, Value),
    In(String, Vec<Value>),
    Like(String, String),
    Null(String, bool),
    Between(String, Value, Value),
    /// A parenthesised `OR` group: `(a = ? OR b = ?)`.
    OrGroup(Vec<Clause>),
    /// Verbatim SQL with no bindings (used for soft-delete scoping).
    RawNoBind(String),
}

/// How a query joins another table.
struct Join {
    kind: &'static str,
    table: String,
    left: String,
    right: String,
}

/// One page of results plus the paging metadata a UI needs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Page<M> {
    /// The rows on this page.
    pub data: Vec<M>,
    /// Total matching rows (ignoring limit/offset).
    pub total: i64,
    pub per_page: i64,
    pub current_page: i64,
    pub last_page: i64,
}

impl<M> Page<M> {
    /// Whether another page follows.
    pub fn has_more(&self) -> bool {
        self.current_page < self.last_page
    }

    /// 1-based index of the first row on this page (0 when empty).
    pub fn from(&self) -> i64 {
        if self.data.is_empty() {
            0
        } else {
            (self.current_page - 1) * self.per_page + 1
        }
    }

    /// 1-based index of the last row on this page (0 when empty).
    pub fn to(&self) -> i64 {
        if self.data.is_empty() {
            0
        } else {
            self.from() + self.data.len() as i64 - 1
        }
    }
}

/// A minimal, typed query builder: `Model::query().where_eq(..).order_by(..).get(&db)`.
pub struct Query<M: Model> {
    clauses: Vec<Clause>,
    orders: Vec<(String, bool)>,
    limit: Option<i64>,
    offset: Option<i64>,
    joins: Vec<Join>,
    /// `false` = exclude soft-deleted rows, `true` = include, `Some(only)` handled
    /// by `only_trashed`.
    with_trashed: bool,
    only_trashed: bool,
    error: Option<String>,
    _marker: PhantomData<M>,
}

impl<M: Model> Default for Query<M> {
    fn default() -> Self {
        Self::new()
    }
}

impl<M: Model> Query<M> {
    pub fn new() -> Self {
        Self {
            clauses: Vec::new(),
            orders: Vec::new(),
            limit: None,
            offset: None,
            joins: Vec::new(),
            with_trashed: false,
            only_trashed: false,
            error: None,
            _marker: PhantomData,
        }
    }

    fn note_invalid(&mut self, column: &str) {
        if self.error.is_none() {
            self.error = Some(format!("invalid column `{column}`"));
        }
    }

    fn push(mut self, column: &str, op: Op, value: Value) -> Self {
        if valid_qualified_ident(column) {
            self.clauses.push(Clause::Cmp(column.to_owned(), op, value));
        } else {
            self.note_invalid(column);
        }
        self
    }

    /// `column IN (..)`. An empty list matches nothing.
    pub fn where_in<V: Into<Value>>(
        mut self,
        column: &str,
        values: impl IntoIterator<Item = V>,
    ) -> Self {
        if valid_qualified_ident(column) {
            let values = values.into_iter().map(Into::into).collect();
            self.clauses.push(Clause::In(column.to_owned(), values));
        } else {
            self.note_invalid(column);
        }
        self
    }

    pub fn where_eq(self, column: &str, value: impl Into<Value>) -> Self {
        self.push(column, Op::Eq, value.into())
    }
    pub fn where_ne(self, column: &str, value: impl Into<Value>) -> Self {
        self.push(column, Op::Ne, value.into())
    }
    pub fn where_lt(self, column: &str, value: impl Into<Value>) -> Self {
        self.push(column, Op::Lt, value.into())
    }
    pub fn where_gt(self, column: &str, value: impl Into<Value>) -> Self {
        self.push(column, Op::Gt, value.into())
    }
    pub fn where_lte(self, column: &str, value: impl Into<Value>) -> Self {
        self.push(column, Op::Le, value.into())
    }
    pub fn where_gte(self, column: &str, value: impl Into<Value>) -> Self {
        self.push(column, Op::Ge, value.into())
    }

    pub fn order_by(mut self, column: &str) -> Self {
        self.set_order(column, true);
        self
    }
    pub fn order_by_desc(mut self, column: &str) -> Self {
        self.set_order(column, false);
        self
    }
    fn set_order(&mut self, column: &str, asc: bool) {
        if valid_qualified_ident(column) {
            // Multiple calls chain (`ORDER BY a ASC, b DESC`) instead of replacing.
            self.orders.push((column.to_owned(), asc));
        } else if self.error.is_none() {
            self.error = Some(format!("invalid column `{column}`"));
        }
    }

    pub fn limit(mut self, n: i64) -> Self {
        self.limit = Some(n.max(0));
        self
    }

    /// Skip `n` rows (paired with [`limit`](Query::limit)).
    pub fn offset(mut self, n: i64) -> Self {
        self.offset = Some(n.max(0));
        self
    }

    /// `column LIKE pattern` (the caller supplies the `%`s).
    pub fn where_like(mut self, column: &str, pattern: impl Into<String>) -> Self {
        if valid_qualified_ident(column) {
            self.clauses
                .push(Clause::Like(column.to_owned(), pattern.into()));
        } else {
            self.note_invalid(column);
        }
        self
    }

    /// `column IS NULL`.
    pub fn where_null(mut self, column: &str) -> Self {
        if valid_qualified_ident(column) {
            self.clauses.push(Clause::Null(column.to_owned(), true));
        } else {
            self.note_invalid(column);
        }
        self
    }

    /// `column IS NOT NULL`.
    pub fn where_not_null(mut self, column: &str) -> Self {
        if valid_qualified_ident(column) {
            self.clauses.push(Clause::Null(column.to_owned(), false));
        } else {
            self.note_invalid(column);
        }
        self
    }

    /// `column BETWEEN low AND high` (inclusive).
    pub fn where_between(
        mut self,
        column: &str,
        low: impl Into<Value>,
        high: impl Into<Value>,
    ) -> Self {
        if valid_qualified_ident(column) {
            self.clauses
                .push(Clause::Between(column.to_owned(), low.into(), high.into()));
        } else {
            self.note_invalid(column);
        }
        self
    }

    /// An `OR` group: every equality in `pairs` is combined with `OR` and the
    /// group is `AND`ed with the rest of the query.
    ///
    /// ```ignore
    /// User::query().where_eq("active", true).or_where_eq(&[("role", "admin".into()), ("role", "owner".into())])
    /// ```
    pub fn or_where_eq(mut self, pairs: &[(&str, Value)]) -> Self {
        let mut group = Vec::new();
        for (column, value) in pairs {
            if !valid_qualified_ident(column) {
                self.note_invalid(column);
                return self;
            }
            group.push(Clause::Cmp((*column).to_owned(), Op::Eq, value.clone()));
        }
        if !group.is_empty() {
            self.clauses.push(Clause::OrGroup(group));
        }
        self
    }

    /// `INNER JOIN other ON left = right` (both sides are `table.column`).
    pub fn join(self, table: &str, left: &str, right: &str) -> Self {
        self.push_join("INNER JOIN", table, left, right)
    }

    /// `LEFT JOIN other ON left = right`.
    pub fn left_join(self, table: &str, left: &str, right: &str) -> Self {
        self.push_join("LEFT JOIN", table, left, right)
    }

    fn push_join(mut self, kind: &'static str, table: &str, left: &str, right: &str) -> Self {
        for ident in [table, left, right] {
            if !valid_qualified_ident(ident) {
                self.note_invalid(ident);
                return self;
            }
        }
        self.joins.push(Join {
            kind,
            table: table.to_owned(),
            left: left.to_owned(),
            right: right.to_owned(),
        });
        self
    }

    /// Include soft-deleted rows (no-op unless the model has `soft_deletes`).
    pub fn with_trashed(mut self) -> Self {
        self.with_trashed = true;
        self
    }

    /// Only soft-deleted rows.
    pub fn only_trashed(mut self) -> Self {
        self.only_trashed = true;
        self
    }

    /// Render the `WHERE`/`JOIN`/`ORDER`/`LIMIT` parts shared by every terminal.
    fn parts(&self, driver: Driver, start_index: usize) -> Result<(QueryParts, AnyArguments)> {
        if let Some(err) = &self.error {
            return Err(Error::Query(err.clone()));
        }
        let mut args = AnyArguments::default();
        let mut idx = start_index;

        // Soft-delete scoping is a plain clause, so it participates in the AND chain.
        let mut clauses: Vec<&Clause> = Vec::new();
        let scope;
        if let Some(column) = M::SOFT_DELETE {
            if self.only_trashed {
                scope = Some(Clause::RawNoBind(format!("{column} IS NOT NULL")));
            } else if !self.with_trashed {
                scope = Some(Clause::RawNoBind(format!("{column} IS NULL")));
            } else {
                scope = None;
            }
        } else {
            scope = None;
        }
        if let Some(scope) = &scope {
            clauses.push(scope);
        }
        clauses.extend(self.clauses.iter());

        let mut where_parts = Vec::new();
        for clause in clauses {
            where_parts.push(render_clause(clause, driver, &mut idx, &mut args)?);
        }

        let joins = self
            .joins
            .iter()
            .map(|j| format!("{} {} ON {} = {}", j.kind, j.table, j.left, j.right))
            .collect::<Vec<_>>()
            .join(" ");

        let order = if self.orders.is_empty() {
            String::new()
        } else {
            let cols: Vec<String> = self
                .orders
                .iter()
                .map(|(c, asc)| format!("{c} {}", if *asc { "ASC" } else { "DESC" }))
                .collect();
            format!(" ORDER BY {}", cols.join(", "))
        };

        let mut tail = order;
        if let Some(n) = self.limit {
            tail.push_str(&format!(" LIMIT {n}"));
        }
        if let Some(n) = self.offset {
            // Postgres/SQLite accept OFFSET without LIMIT; MySQL does not.
            if self.limit.is_none() && driver == Driver::MySql {
                tail.push_str(" LIMIT 18446744073709551615");
            }
            tail.push_str(&format!(" OFFSET {n}"));
        }

        Ok((
            QueryParts {
                joins,
                where_clause: if where_parts.is_empty() {
                    String::new()
                } else {
                    format!(" WHERE {}", where_parts.join(" AND "))
                },
                tail,
            },
            args,
        ))
    }

    fn build(&self, driver: Driver) -> Result<(String, AnyArguments)> {
        let (parts, args) = self.parts(driver, 1)?;
        let columns: Vec<String> = M::COLUMNS
            .iter()
            .map(|c| format!("{}.{}", M::TABLE, c))
            .collect();
        // Qualify the selection so a join can't make a column ambiguous.
        let mut sql = format!("SELECT {} FROM {}", columns.join(", "), M::TABLE);
        if !parts.joins.is_empty() {
            sql.push(' ');
            sql.push_str(&parts.joins);
        }
        sql.push_str(&parts.where_clause);
        sql.push_str(&parts.tail);
        Ok((sql, args))
    }

    /// Execute and collect all matching rows.
    pub async fn get(self, db: &Database) -> Result<Vec<M>> {
        let (sql, args) = self.build(db.driver())?;
        let rows = sqlx::query_with(sqlx::AssertSqlSafe(sql), args)
            .fetch_all(db.pool())
            .await?;
        rows.iter().map(M::from_row).collect()
    }

    /// Execute and return the first matching row, if any.
    pub async fn first(mut self, db: &Database) -> Result<Option<M>> {
        self.limit = Some(1);
        Ok(self.get(db).await?.into_iter().next())
    }

    /// Whether any row matches.
    pub async fn exists(self, db: &Database) -> Result<bool> {
        Ok(self.count(db).await? > 0)
    }

    /// `COUNT(*)` for the current constraints (ignores limit/offset).
    pub async fn count(self, db: &Database) -> Result<i64> {
        self.aggregate(db, "COUNT", "*")
            .await
            .map(|v| v.unwrap_or(0))
    }

    /// `SUM(column)`, `None` when no rows match.
    pub async fn sum(self, db: &Database, column: &str) -> Result<Option<f64>> {
        self.aggregate_f64(db, "SUM", column).await
    }

    /// `AVG(column)`.
    pub async fn avg(self, db: &Database, column: &str) -> Result<Option<f64>> {
        self.aggregate_f64(db, "AVG", column).await
    }

    /// `MIN(column)` as an integer.
    pub async fn min(self, db: &Database, column: &str) -> Result<Option<i64>> {
        self.aggregate(db, "MIN", column).await
    }

    /// `MAX(column)` as an integer.
    pub async fn max(self, db: &Database, column: &str) -> Result<Option<i64>> {
        self.aggregate(db, "MAX", column).await
    }

    fn aggregate_sql(
        &self,
        driver: Driver,
        func: &str,
        column: &str,
    ) -> Result<(String, AnyArguments)> {
        if column != "*" && !valid_qualified_ident(column) {
            return Err(Error::Query(format!("invalid column `{column}`")));
        }
        // Limit/offset must not constrain an aggregate.
        let mut bare = self.clone_shallow();
        bare.orders.clear();
        bare.joins.clear();
        let (parts, args) = bare.parts(driver, 1)?;
        let sql = format!(
            "SELECT {func}({column}) AS agg FROM {}{}",
            M::TABLE,
            parts.where_clause
        );
        Ok((sql, args))
    }

    async fn aggregate(self, db: &Database, func: &str, column: &str) -> Result<Option<i64>> {
        let (sql, args) = self.aggregate_sql(db.driver(), func, column)?;
        let row = sqlx::query_with(sqlx::AssertSqlSafe(sql), args)
            .fetch_one(db.pool())
            .await?;
        Ok(row.try_get::<i64, _>("agg").ok())
    }

    async fn aggregate_f64(self, db: &Database, func: &str, column: &str) -> Result<Option<f64>> {
        let (sql, args) = self.aggregate_sql(db.driver(), func, column)?;
        let row = sqlx::query_with(sqlx::AssertSqlSafe(sql), args)
            .fetch_one(db.pool())
            .await?;
        // Backends disagree on the type of SUM/AVG: try float, then integer.
        if let Ok(v) = row.try_get::<f64, _>("agg") {
            return Ok(Some(v));
        }
        Ok(row.try_get::<i64, _>("agg").ok().map(|v| v as f64))
    }

    /// One page of results plus the total row count — Laravel's `paginate()`.
    ///
    /// `page` is 1-based; values below 1 are treated as 1.
    pub async fn paginate(self, db: &Database, page: i64, per_page: i64) -> Result<Page<M>> {
        let per_page = per_page.max(1);
        let page = page.max(1);
        let total = self.clone_shallow().count(db).await?;
        let last_page = ((total as f64) / (per_page as f64)).ceil() as i64;

        let data = self
            .limit(per_page)
            .offset((page - 1) * per_page)
            .get(db)
            .await?;

        Ok(Page {
            data,
            total,
            per_page,
            current_page: page,
            last_page: last_page.max(1),
        })
    }

    /// Process matching rows in batches of `size`, keyed on the primary key so a
    /// large table never has to be held in memory at once.
    pub async fn chunk<F>(self, db: &Database, size: i64, mut handle: F) -> Result<i64>
    where
        F: FnMut(Vec<M>) -> Result<()>,
    {
        let size = size.max(1);
        let mut processed = 0i64;
        let mut page = 0i64;
        loop {
            let batch = self
                .clone_shallow()
                .limit(size)
                .offset(page * size)
                .get(db)
                .await?;
            if batch.is_empty() {
                return Ok(processed);
            }
            processed += batch.len() as i64;
            let count = batch.len() as i64;
            handle(batch)?;
            if count < size {
                return Ok(processed);
            }
            page += 1;
        }
    }

    /// `UPDATE <table> SET … WHERE …`, returning the number of affected rows.
    pub async fn update(self, db: &Database, values: &[(&str, Value)]) -> Result<u64> {
        if values.is_empty() {
            return Ok(0);
        }
        let driver = db.driver();
        let mut args = AnyArguments::default();
        let mut idx = 1usize;
        let mut sets = Vec::new();
        for (column, value) in values {
            if !valid_qualified_ident(column) {
                return Err(Error::Query(format!("invalid column `{column}`")));
            }
            sets.push(format!("{column} = {}", placeholder(driver, idx)));
            idx += 1;
            bind_value(&mut args, value)?;
        }

        let (parts, where_args) = self.parts(driver, idx)?;
        // The SET bindings come first, then the WHERE bindings, in order.
        let mut all = args;
        append_arguments(&mut all, where_args, self.binding_values(), driver)?;
        let sql = format!(
            "UPDATE {} SET {}{}",
            M::TABLE,
            sets.join(", "),
            parts.where_clause
        );
        let result = sqlx::query_with(sqlx::AssertSqlSafe(sql), all)
            .execute(db.pool())
            .await?;
        Ok(result.rows_affected())
    }

    /// `DELETE FROM <table> WHERE …`, returning the number of affected rows.
    ///
    /// For a soft-deleting model this is a **hard** delete; use
    /// [`soft_delete`](Query::soft_delete) for the reversible one.
    pub async fn delete(self, db: &Database) -> Result<u64> {
        let driver = db.driver();
        let (parts, args) = self.parts(driver, 1)?;
        let sql = format!("DELETE FROM {}{}", M::TABLE, parts.where_clause);
        let result = sqlx::query_with(sqlx::AssertSqlSafe(sql), args)
            .execute(db.pool())
            .await?;
        Ok(result.rows_affected())
    }

    /// Set the soft-delete column to now for every matching row.
    pub async fn soft_delete(self, db: &Database) -> Result<u64> {
        let Some(column) = M::SOFT_DELETE else {
            return Err(Error::Query(format!(
                "`{}` has no soft-delete column (add #[model(soft_deletes)])",
                M::TABLE
            )));
        };
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        self.update(db, &[(column, Value::Int(now))]).await
    }

    /// Clear the soft-delete column for every matching (trashed) row.
    pub async fn restore(self, db: &Database) -> Result<u64> {
        let Some(column) = M::SOFT_DELETE else {
            return Err(Error::Query(format!(
                "`{}` has no soft-delete column (add #[model(soft_deletes)])",
                M::TABLE
            )));
        };
        self.only_trashed()
            .update(db, &[(column, Value::Null)])
            .await
    }

    /// The bound values in clause order (used when composing UPDATE bindings).
    fn binding_values(&self) -> Vec<Value> {
        let mut out = Vec::new();
        for clause in &self.clauses {
            collect_values(clause, &mut out);
        }
        out
    }

    /// A copy of the constraints (not the paging), so a terminal can be run twice.
    fn clone_shallow(&self) -> Query<M> {
        Query {
            clauses: self.clauses.iter().map(clone_clause).collect(),
            orders: self.orders.clone(),
            limit: None,
            offset: None,
            joins: self
                .joins
                .iter()
                .map(|j| Join {
                    kind: j.kind,
                    table: j.table.clone(),
                    left: j.left.clone(),
                    right: j.right.clone(),
                })
                .collect(),
            with_trashed: self.with_trashed,
            only_trashed: self.only_trashed,
            error: self.error.clone(),
            _marker: PhantomData,
        }
    }
}

/// The rendered fragments of a query.
struct QueryParts {
    joins: String,
    where_clause: String,
    tail: String,
}

fn clone_clause(clause: &Clause) -> Clause {
    match clause {
        Clause::Cmp(c, op, v) => Clause::Cmp(c.clone(), *op, v.clone()),
        Clause::In(c, vs) => Clause::In(c.clone(), vs.clone()),
        Clause::Like(c, p) => Clause::Like(c.clone(), p.clone()),
        Clause::Null(c, is_null) => Clause::Null(c.clone(), *is_null),
        Clause::Between(c, a, b) => Clause::Between(c.clone(), a.clone(), b.clone()),
        Clause::OrGroup(group) => Clause::OrGroup(group.iter().map(clone_clause).collect()),
        Clause::RawNoBind(sql) => Clause::RawNoBind(sql.clone()),
    }
}

fn collect_values(clause: &Clause, out: &mut Vec<Value>) {
    match clause {
        Clause::Cmp(_, _, v) => out.push(v.clone()),
        Clause::In(_, vs) => out.extend(vs.iter().cloned()),
        Clause::Like(_, p) => out.push(Value::Text(p.clone())),
        Clause::Between(_, a, b) => {
            out.push(a.clone());
            out.push(b.clone());
        }
        Clause::OrGroup(group) => {
            for inner in group {
                collect_values(inner, out);
            }
        }
        Clause::Null(_, _) | Clause::RawNoBind(_) => {}
    }
}

/// Re-bind `values` onto `target` (the `Any` driver has no way to concatenate two
/// argument lists, so an UPDATE rebuilds the WHERE bindings in order).
fn append_arguments(
    target: &mut AnyArguments,
    _placeholder_args: AnyArguments,
    values: Vec<Value>,
    _driver: Driver,
) -> Result<()> {
    for value in values {
        bind_value(target, &value)?;
    }
    Ok(())
}

/// Render one clause, binding its values and advancing the placeholder index.
fn render_clause(
    clause: &Clause,
    driver: Driver,
    idx: &mut usize,
    args: &mut AnyArguments,
) -> Result<String> {
    Ok(match clause {
        Clause::Cmp(col, op, value) => {
            let sql = format!("{col} {} {}", op.sql(), placeholder(driver, *idx));
            *idx += 1;
            bind_value(args, value)?;
            sql
        }
        Clause::In(col, values) => {
            if values.is_empty() {
                "1 = 0".to_string()
            } else {
                let phs: Vec<String> = values
                    .iter()
                    .map(|_| {
                        let p = placeholder(driver, *idx);
                        *idx += 1;
                        p
                    })
                    .collect();
                for value in values {
                    bind_value(args, value)?;
                }
                format!("{col} IN ({})", phs.join(", "))
            }
        }
        Clause::Like(col, pattern) => {
            let sql = format!("{col} LIKE {}", placeholder(driver, *idx));
            *idx += 1;
            bind_value(args, &Value::Text(pattern.clone()))?;
            sql
        }
        Clause::Null(col, is_null) => {
            if *is_null {
                format!("{col} IS NULL")
            } else {
                format!("{col} IS NOT NULL")
            }
        }
        Clause::Between(col, low, high) => {
            let a = placeholder(driver, *idx);
            *idx += 1;
            let b = placeholder(driver, *idx);
            *idx += 1;
            bind_value(args, low)?;
            bind_value(args, high)?;
            format!("{col} BETWEEN {a} AND {b}")
        }
        Clause::OrGroup(group) => {
            let mut parts = Vec::new();
            for inner in group {
                parts.push(render_clause(inner, driver, idx, args)?);
            }
            format!("({})", parts.join(" OR "))
        }
        Clause::RawNoBind(sql) => sql.clone(),
    })
}

fn bind_value(args: &mut AnyArguments, value: &Value) -> Result<()> {
    let result = match value {
        Value::Int(i) => args.add(*i),
        Value::Real(f) => args.add(*f),
        Value::Text(s) => args.add(s.clone()),
        // Booleans map to INTEGER 0/1 columns (the Any driver can't read a
        // native BOOLEAN column, so models never use one).
        Value::Bool(b) => args.add(*b as i64),
        Value::Null => args.add(None::<i64>),
    };
    result.map_err(|e| Error::Query(e.to_string()))
}
