//! Active-Record-style models — Elyra's Eloquent, thin over sqlx.
//!
//! `#[derive(Model)]` generates CRUD (`all` / `find` / `insert` / `update` /
//! `delete` / `save`) plus a small typed [`Query`] builder. It's a thin layer
//! over the `Database` pool we already have — not a second ORM engine.
//!
//! Placeholders are rendered per driver (`?` for sqlite/mysql, `$n` for
//! postgres) since the sqlx `Any` driver doesn't translate them; inserts use
//! `RETURNING` on sqlite/postgres and `last_insert_id()` on MySQL.
//!
//! v1 assumptions (documented, may loosen later): the primary key is an
//! `i64` autoincrement column (a value of `0` means "unsaved"), and column names
//! equal field names.

use std::collections::HashMap;
use std::marker::PhantomData;

use sqlx::any::{AnyArguments, AnyRow};
use sqlx::Arguments;

use crate::error::{Error, Result};
use crate::{Database, Driver};

/// Metadata a `#[derive(Model)]` type provides, used by the [`Query`] builder.
pub trait Model: Sized + Send + Unpin {
    const TABLE: &'static str;
    const PK: &'static str;
    const COLUMNS: &'static [&'static str];

    /// Map a row into `Self`. Generated by the derive.
    fn from_row(row: &AnyRow) -> Result<Self>;

    /// Read an `i64`-valued column from this instance by name (used by eager
    /// loading to collect keys / group results). Generated by the derive;
    /// returns `None` for non-integer columns.
    fn get_i64(&self, column: &str) -> Option<i64>;
}

/// Eager-load a `has_many` relation for a batch of parents: one `WHERE fk IN
/// (..)` query, grouped by foreign key. Returns a map keyed by parent PK value.
pub async fn eager_has_many<P: Model, C: Model>(
    db: &Database,
    parents: &[P],
    parent_pk: &str,
    foreign_key: &str,
) -> Result<HashMap<i64, Vec<C>>> {
    let ids: Vec<i64> = parents
        .iter()
        .filter_map(|p| p.get_i64(parent_pk))
        .collect();
    let mut grouped: HashMap<i64, Vec<C>> = HashMap::new();
    if ids.is_empty() {
        return Ok(grouped);
    }
    let children = Query::<C>::new().where_in(foreign_key, ids).get(db).await?;
    for child in children {
        if let Some(key) = child.get_i64(foreign_key) {
            grouped.entry(key).or_default().push(child);
        }
    }
    Ok(grouped)
}

/// Eager-load a `has_one` relation (the first child per parent key).
pub async fn eager_has_one<P: Model, C: Model>(
    db: &Database,
    parents: &[P],
    parent_pk: &str,
    foreign_key: &str,
) -> Result<HashMap<i64, C>> {
    let grouped = eager_has_many::<P, C>(db, parents, parent_pk, foreign_key).await?;
    Ok(grouped
        .into_iter()
        .filter_map(|(key, children)| children.into_iter().next().map(|c| (key, c)))
        .collect())
}

/// Eager-load a `belongs_to` relation for a batch of children: query the parents
/// whose PK is in the children's foreign keys. Returns a map keyed by parent PK,
/// so the caller can look up `map[&child.fk]`.
pub async fn eager_belongs_to<C: Model, P: Model>(
    db: &Database,
    children: &[C],
    foreign_key: &str,
    parent_pk: &str,
) -> Result<HashMap<i64, P>> {
    let ids: Vec<i64> = children
        .iter()
        .filter_map(|c| c.get_i64(foreign_key))
        .collect();
    let mut by_id: HashMap<i64, P> = HashMap::new();
    if ids.is_empty() {
        return Ok(by_id);
    }
    let parents = Query::<P>::new().where_in(parent_pk, ids).get(db).await?;
    for parent in parents {
        if let Some(key) = parent.get_i64(parent_pk) {
            by_id.insert(key, parent);
        }
    }
    Ok(by_id)
}

/// Render the placeholder for bind position `index` (1-based) on `driver`.
pub fn placeholder(driver: Driver, index: usize) -> String {
    match driver {
        Driver::Postgres => format!("${index}"),
        _ => "?".to_string(),
    }
}

/// Render `count` comma-separated placeholders starting at position 1.
pub fn placeholders(driver: Driver, count: usize) -> String {
    (1..=count)
        .map(|i| placeholder(driver, i))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Reject anything that isn't a bare SQL identifier (columns can't be bound).
fn valid_ident(ident: &str) -> bool {
    !ident.is_empty() && ident.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// A bindable scalar for the query builder.
#[derive(Clone, Debug)]
pub enum Value {
    Int(i64),
    Real(f64),
    Text(String),
    Bool(bool),
    Null,
}

impl From<i64> for Value {
    fn from(v: i64) -> Self {
        Value::Int(v)
    }
}
impl From<i32> for Value {
    fn from(v: i32) -> Self {
        Value::Int(v as i64)
    }
}
impl From<bool> for Value {
    fn from(v: bool) -> Self {
        Value::Bool(v)
    }
}
impl From<f64> for Value {
    fn from(v: f64) -> Self {
        Value::Real(v)
    }
}
impl From<&str> for Value {
    fn from(v: &str) -> Self {
        Value::Text(v.to_owned())
    }
}
impl From<String> for Value {
    fn from(v: String) -> Self {
        Value::Text(v)
    }
}

#[derive(Clone, Copy)]
enum Op {
    Eq,
    Ne,
    Lt,
    Gt,
    Le,
    Ge,
}

impl Op {
    fn sql(self) -> &'static str {
        match self {
            Op::Eq => "=",
            Op::Ne => "<>",
            Op::Lt => "<",
            Op::Gt => ">",
            Op::Le => "<=",
            Op::Ge => ">=",
        }
    }
}

enum Clause {
    Cmp(String, Op, Value),
    In(String, Vec<Value>),
}

/// A minimal, typed query builder: `Model::query().where_eq(..).order_by(..).get(&db)`.
pub struct Query<M: Model> {
    clauses: Vec<Clause>,
    order: Option<(String, bool)>,
    limit: Option<i64>,
    error: Option<String>,
    _marker: PhantomData<M>,
}

impl<M: Model> Default for Query<M> {
    fn default() -> Self {
        Self::new()
    }
}

impl<M: Model> Query<M> {
    pub fn new() -> Self {
        Self {
            clauses: Vec::new(),
            order: None,
            limit: None,
            error: None,
            _marker: PhantomData,
        }
    }

    fn note_invalid(&mut self, column: &str) {
        if self.error.is_none() {
            self.error = Some(format!("invalid column `{column}`"));
        }
    }

    fn push(mut self, column: &str, op: Op, value: Value) -> Self {
        if valid_ident(column) {
            self.clauses.push(Clause::Cmp(column.to_owned(), op, value));
        } else {
            self.note_invalid(column);
        }
        self
    }

    /// `column IN (..)`. An empty list matches nothing.
    pub fn where_in<V: Into<Value>>(
        mut self,
        column: &str,
        values: impl IntoIterator<Item = V>,
    ) -> Self {
        if valid_ident(column) {
            let values = values.into_iter().map(Into::into).collect();
            self.clauses.push(Clause::In(column.to_owned(), values));
        } else {
            self.note_invalid(column);
        }
        self
    }

    pub fn where_eq(self, column: &str, value: impl Into<Value>) -> Self {
        self.push(column, Op::Eq, value.into())
    }
    pub fn where_ne(self, column: &str, value: impl Into<Value>) -> Self {
        self.push(column, Op::Ne, value.into())
    }
    pub fn where_lt(self, column: &str, value: impl Into<Value>) -> Self {
        self.push(column, Op::Lt, value.into())
    }
    pub fn where_gt(self, column: &str, value: impl Into<Value>) -> Self {
        self.push(column, Op::Gt, value.into())
    }
    pub fn where_lte(self, column: &str, value: impl Into<Value>) -> Self {
        self.push(column, Op::Le, value.into())
    }
    pub fn where_gte(self, column: &str, value: impl Into<Value>) -> Self {
        self.push(column, Op::Ge, value.into())
    }

    pub fn order_by(mut self, column: &str) -> Self {
        self.set_order(column, true);
        self
    }
    pub fn order_by_desc(mut self, column: &str) -> Self {
        self.set_order(column, false);
        self
    }
    fn set_order(&mut self, column: &str, asc: bool) {
        if valid_ident(column) {
            self.order = Some((column.to_owned(), asc));
        } else if self.error.is_none() {
            self.error = Some(format!("invalid column `{column}`"));
        }
    }

    pub fn limit(mut self, n: i64) -> Self {
        self.limit = Some(n);
        self
    }

    fn build(&self, driver: Driver) -> Result<(String, AnyArguments)> {
        if let Some(err) = &self.error {
            return Err(Error::Query(err.clone()));
        }

        let mut sql = format!("SELECT {} FROM {}", M::COLUMNS.join(", "), M::TABLE);
        let mut args = AnyArguments::default();

        if !self.clauses.is_empty() {
            let mut idx = 1usize;
            let mut parts = Vec::new();
            for clause in &self.clauses {
                match clause {
                    Clause::Cmp(col, op, value) => {
                        parts.push(format!("{col} {} {}", op.sql(), placeholder(driver, idx)));
                        idx += 1;
                        bind_value(&mut args, value)?;
                    }
                    Clause::In(col, values) => {
                        if values.is_empty() {
                            parts.push("1 = 0".to_string());
                        } else {
                            let phs: Vec<String> = values
                                .iter()
                                .map(|_| {
                                    let p = placeholder(driver, idx);
                                    idx += 1;
                                    p
                                })
                                .collect();
                            parts.push(format!("{col} IN ({})", phs.join(", ")));
                            for value in values {
                                bind_value(&mut args, value)?;
                            }
                        }
                    }
                }
            }
            sql.push_str(" WHERE ");
            sql.push_str(&parts.join(" AND "));
        }

        if let Some((col, asc)) = &self.order {
            sql.push_str(&format!(
                " ORDER BY {col} {}",
                if *asc { "ASC" } else { "DESC" }
            ));
        }
        if let Some(n) = self.limit {
            sql.push_str(&format!(" LIMIT {n}"));
        }

        Ok((sql, args))
    }

    /// Execute and collect all matching rows.
    pub async fn get(self, db: &Database) -> Result<Vec<M>> {
        let (sql, args) = self.build(db.driver())?;
        let rows = sqlx::query_with(sqlx::AssertSqlSafe(sql), args)
            .fetch_all(db.pool())
            .await?;
        rows.iter().map(M::from_row).collect()
    }

    /// Execute and return the first matching row, if any.
    pub async fn first(mut self, db: &Database) -> Result<Option<M>> {
        self.limit = Some(1);
        Ok(self.get(db).await?.into_iter().next())
    }
}

fn bind_value(args: &mut AnyArguments, value: &Value) -> Result<()> {
    let result = match value {
        Value::Int(i) => args.add(*i),
        Value::Real(f) => args.add(*f),
        Value::Text(s) => args.add(s.clone()),
        // Booleans map to INTEGER 0/1 columns (the Any driver can't read a
        // native BOOLEAN column, so models never use one).
        Value::Bool(b) => args.add(*b as i64),
        Value::Null => args.add(None::<i64>),
    };
    result.map_err(|e| Error::Query(e.to_string()))
}
