//! The resource registries behind `rata make:resource` (RFC 0001).
//!
//! A resource lives in two folders, one per half:
//!
//! - `src/resources/<name>/mod.rs` exposes `commands()`, `migrations()`,
//!   `seeders()` and `ABILITIES`;
//! - `<frontend>/src/resources/<plural>/index.js` exports `routes` and `nav`.
//!
//! The two registries that gather them — `src/resources/mod.rs` and
//! `<frontend>/src/resources/index.js` — are owned by rata and regenerated from
//! the folder listing, so adding (or deleting) a resource never means editing
//! `main.rs`. That needs wiring once, which [`wiring_hints`] checks for without
//! touching the file.

use std::path::{Path, PathBuf};

/// First line of every file rata manages; a registry without it is the user's
/// and is never overwritten.
const MARKER: &str = "managed by rata";

/// Where the two registries live for a project.
pub struct Layout {
    /// `src/resources/`
    pub rust: PathBuf,
    /// `<frontend>/src/resources/`
    pub js: PathBuf,
    /// `src/main.rs`
    pub main_rs: PathBuf,
    /// `<frontend>/src/routes.js`
    pub routes_js: PathBuf,
}

impl Layout {
    pub fn new(root: &Path, frontend_dir: &Path) -> Self {
        let frontend = root.join(frontend_dir);
        Layout {
            rust: root.join("src").join("resources"),
            js: frontend.join("src").join("resources"),
            main_rs: root.join("src").join("main.rs"),
            routes_js: frontend.join("src").join("routes.js"),
        }
    }
}

/// The resource folders under `dir` that contain `entry`, sorted. A folder whose
/// name isn't an identifier is an error rather than silently skipped: it would
/// otherwise vanish from the app with no explanation.
fn resources_in(dir: &Path, entry: &str) -> Result<Vec<String>, String> {
    let Ok(read) = std::fs::read_dir(dir) else {
        return Ok(Vec::new());
    };
    let mut names = Vec::new();
    for item in read {
        let item = item.map_err(|e| format!("{}: {e}", dir.display()))?;
        if !item.path().join(entry).is_file() {
            continue;
        }
        let name = item.file_name().to_string_lossy().into_owned();
        if !is_ident(&name) {
            return Err(format!(
                "{}: a resource folder name must be snake_case (letters, digits, `_`)",
                item.path().display()
            ));
        }
        names.push(name);
    }
    names.sort();
    Ok(names)
}

fn is_ident(name: &str) -> bool {
    let mut chars = name.chars();
    matches!(chars.next(), Some(c) if c.is_ascii_lowercase() || c == '_')
        && chars.all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
}

/// `src/resources/mod.rs` for the given resource modules. `seed_order` is the
/// same modules in the order their seeders run: a parent's before its
/// children's, as its migration's is.
pub fn rust_registry(modules: &[String], seed_order: &[String]) -> String {
    let mut out = format!(
        "//! Resources — {MARKER}. Regenerated by `rata make:resource` and\n\
         //! `rata resources:sync` from the folders next to this file; change a\n\
         //! resource in its own folder, not here.\n\n"
    );
    for m in modules {
        out.push_str(&format!("pub mod {m};\n"));
    }
    if !modules.is_empty() {
        out.push('\n');
    }

    let gather_in = |modules: &[String], call: &str| -> String {
        if modules.is_empty() {
            return "    Vec::new()\n".into();
        }
        let mut body = "    let mut all = Vec::new();\n".to_string();
        for m in modules {
            body.push_str(&format!("    all.extend({m}::{call});\n"));
        }
        body.push_str("    all\n");
        body
    };
    let gather = |call: &str| gather_in(modules, call);

    out.push_str("/// Every resource's commands: `App::new().commands(resources::commands())`.\n");
    out.push_str("pub fn commands() -> Vec<Box<dyn elyra::Command>> {\n");
    out.push_str(&gather("commands()"));
    out.push_str("}\n\n");
    out.push_str("/// Every resource's migrations: `.migrations(resources::migrations())`.\n");
    out.push_str("pub fn migrations() -> Vec<Box<dyn elyra::db::RustMigration>> {\n");
    out.push_str(&gather("migrations()"));
    out.push_str("}\n\n");
    out.push_str("/// Every resource's seeders: `.seeders(resources::seeders())`.\n");
    out.push_str("pub fn seeders() -> Vec<Box<dyn elyra::seeder::Seeder>> {\n");
    out.push_str(&gather_in(seed_order, "seeders()"));
    out.push_str("}\n\n");
    out.push_str(
        "/// The abilities the resources' commands require — commands are denied until\n\
         /// the app grants them: `.allow_abilities(resources::abilities())`.\n",
    );
    out.push_str("pub fn abilities() -> Vec<&'static str> {\n");
    out.push_str(&gather("ABILITIES.iter().copied()"));
    out.push_str("}\n");
    out
}

/// `modules` in the order of their migrations' versions — generation order,
/// which puts a parent first. A resource without a migration goes first.
fn by_migration(dir: &Path, modules: &[String]) -> Vec<String> {
    let mut ordered: Vec<(u64, String)> = modules
        .iter()
        .map(|m| {
            let version = std::fs::read_to_string(dir.join(m).join("migration.rs"))
                .ok()
                .and_then(|text| crate::resource_generate::existing_version(&text))
                .and_then(|v| v.parse().ok())
                .unwrap_or(0);
            (version, m.clone())
        })
        .collect();
    ordered.sort();
    ordered.into_iter().map(|(_, m)| m).collect()
}

/// `<frontend>/src/resources/index.js` for the given resource folders.
pub fn js_registry(modules: &[String]) -> String {
    let mut out = format!(
        "// Resources — {MARKER}. Regenerated by `rata make:resource` and\n\
         // `rata resources:sync` from the folders next to this file; change a\n\
         // resource in its own index.js, not here.\n"
    );
    for m in modules {
        out.push_str(&format!("import * as {m} from \"./{m}/index.js\";\n"));
    }
    out.push_str(&format!("\nconst all = [{}];\n\n", modules.join(", ")));
    out.push_str(
        "/** Every resource's pages, merged into the app's routes. */\n\
         export const routes = Object.assign({}, ...all.map((r) => r.routes ?? {}));\n\n\
         /** Links for the app's navigation: `{ label, path }`. */\n\
         export const nav = all.flatMap((r) => r.nav ?? []);\n",
    );
    out
}

/// Write `contents` to a registry, refusing to replace a file rata doesn't own.
/// Returns whether the file changed.
fn write_managed(path: &Path, contents: &str) -> Result<bool, String> {
    match std::fs::read_to_string(path) {
        Ok(existing) if existing == contents => return Ok(false),
        Ok(existing) if !existing.lines().next().unwrap_or("").contains(MARKER) => {
            return Err(format!(
                "{} exists and isn't managed by rata — move it aside (rata never \
                 overwrites your files)",
                path.display()
            ));
        }
        _ => {}
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("{}: {e}", parent.display()))?;
    }
    std::fs::write(path, contents).map_err(|e| format!("{}: {e}", path.display()))?;
    Ok(true)
}

/// Regenerate both registries from the resource folders. The Rust one is
/// written once a `src/resources/` exists; the frontend one once its folder
/// exists (a project without views has none). Returns the files that changed.
pub fn sync(layout: &Layout) -> Result<Vec<PathBuf>, String> {
    let mut changed = Vec::new();
    if layout.rust.is_dir() {
        let path = layout.rust.join("mod.rs");
        let modules = resources_in(&layout.rust, "mod.rs")?;
        let seed_order = by_migration(&layout.rust, &modules);
        if write_managed(&path, &rust_registry(&modules, &seed_order))? {
            changed.push(path);
        }
    }
    if layout.js.is_dir() {
        let path = layout.js.join("index.js");
        if write_managed(&path, &js_registry(&resources_in(&layout.js, "index.js")?))? {
            changed.push(path);
        }
    }
    Ok(changed)
}

/// The edits the app still needs to use its resources — read-only: rata never
/// edits `main.rs` or `routes.js`, it prints what's missing. Empty once wired.
pub fn wiring_hints(layout: &Layout) -> Vec<String> {
    let mut hints = Vec::new();
    if layout.rust.join("mod.rs").is_file() {
        let main = std::fs::read_to_string(&layout.main_rs).unwrap_or_default();
        let mut missing = Vec::new();
        if !main.contains("mod resources;") {
            missing.push("mod resources;              // with your other `mod`s");
        }
        let calls: Vec<&str> = [
            (
                "resources::commands()",
                "    .commands(resources::commands())",
            ),
            (
                "resources::migrations()",
                "    .migrations(resources::migrations())",
            ),
            ("resources::seeders()", "    .seeders(resources::seeders())"),
            (
                "resources::abilities()",
                "    .allow_abilities(resources::abilities())",
            ),
        ]
        .into_iter()
        .filter(|(call, _)| !main.contains(call))
        .map(|(_, line)| line)
        .collect();
        if !calls.is_empty() {
            missing.push("App::new()                  // on your builder:");
            missing.extend(calls);
        }
        if !missing.is_empty() {
            hints.push(format!(
                "In {} (once — every later resource is picked up automatically):\n  {}",
                layout.main_rs.display(),
                missing.join("\n  ")
            ));
        }
    }
    if layout.js.join("index.js").is_file() {
        let routes = std::fs::read_to_string(&layout.routes_js).unwrap_or_default();
        if !routes.contains("./resources/index.js") {
            hints.push(format!(
                "In {} (once), merge the resources' pages into your routes:\n  \
                 import {{ routes as resourceRoutes }} from \"./resources/index.js\";\n  \
                 export const routes = {{ /* your pages */ ...resourceRoutes }};",
                layout.routes_js.display()
            ));
        }
    }
    hints
}

/// `rata resources:sync` — rebuild the registries, e.g. after deleting or
/// renaming a resource folder by hand.
pub fn sync_command(cfg: &crate::config::Config) -> Result<(), String> {
    let layout = Layout::new(&cfg.root, Path::new(&cfg.frontend_dir));
    let changed = sync(&layout)?;
    if changed.is_empty() {
        println!("Registries are up to date.");
    }
    for path in &changed {
        println!("Updated {}", path.display());
    }
    for hint in wiring_hints(&layout) {
        println!("\n{hint}");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn project(tag: &str) -> (PathBuf, Layout) {
        let root = std::env::temp_dir().join(format!("rata-res-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("src")).unwrap();
        let layout = Layout::new(&root, Path::new("app"));
        (root, layout)
    }

    fn touch(path: &Path, contents: &str) {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, contents).unwrap();
    }

    #[test]
    fn rust_registry_gathers_every_module() {
        let src = rust_registry(
            &["customer".into(), "invoice".into()],
            &["invoice".into(), "customer".into()],
        );
        assert!(src.starts_with("//! Resources — managed by rata."));
        assert!(src.contains("pub mod customer;\npub mod invoice;\n"));
        assert!(src.contains(
            "    all.extend(customer::commands());\n    all.extend(invoice::commands());"
        ));
        assert!(src.contains("all.extend(invoice::migrations());"));
        assert!(src.contains("all.extend(customer::ABILITIES.iter().copied());"));
        assert!(
            src.contains(
                "    all.extend(invoice::seeders());\n    all.extend(customer::seeders());"
            ),
            "seeders run in seed order: {src}"
        );
    }

    #[test]
    fn an_empty_registry_still_type_checks() {
        // No `let mut all` with nothing pushed (an unused-mut warning, and no
        // element type to infer) — just an empty Vec of the return type.
        let src = rust_registry(&[], &[]);
        assert!(!src.contains("pub mod"));
        assert_eq!(src.matches("    Vec::new()\n").count(), 4);
    }

    #[test]
    fn js_registry_merges_routes_and_nav() {
        let src = js_registry(&["customers".into(), "invoices".into()]);
        assert!(src.starts_with("// Resources — managed by rata."));
        assert!(src.contains("import * as customers from \"./customers/index.js\";"));
        assert!(src.contains("const all = [customers, invoices];"));
        assert_eq!(js_registry(&[]).matches("const all = [];").count(), 1);
    }

    #[test]
    fn rata_new_scaffolds_the_empty_registry() {
        // `rata new` ships the frontend registry so `routes.js` can import it
        // from day one; it must be exactly what a sync would write.
        let (_, scaffolded) = crate::scaffold::FILES
            .iter()
            .find(|(path, _)| *path == "app/src/resources/index.js")
            .expect("scaffolded");
        assert_eq!(*scaffolded, js_registry(&[]));
    }

    #[test]
    fn sync_lists_folders_and_is_idempotent() {
        let (root, layout) = project("sync");
        touch(&layout.rust.join("invoice/mod.rs"), "");
        touch(&layout.rust.join("customer/mod.rs"), "");
        std::fs::create_dir_all(layout.rust.join("notes")).unwrap(); // no mod.rs: not a resource
        touch(&layout.js.join("customers/index.js"), "");

        let changed = sync(&layout).unwrap();
        assert_eq!(changed.len(), 2);
        let rs = std::fs::read_to_string(layout.rust.join("mod.rs")).unwrap();
        assert!(rs.contains("pub mod customer;\npub mod invoice;\n"), "{rs}");
        assert!(!rs.contains("notes"));
        let js = std::fs::read_to_string(layout.js.join("index.js")).unwrap();
        assert!(js.contains("const all = [customers];"));

        assert!(
            sync(&layout).unwrap().is_empty(),
            "a second sync changes nothing"
        );

        // Deleting a resource by hand, then syncing, drops it.
        std::fs::remove_dir_all(layout.rust.join("invoice")).unwrap();
        assert_eq!(sync(&layout).unwrap(), [layout.rust.join("mod.rs")]);
        let rs = std::fs::read_to_string(layout.rust.join("mod.rs")).unwrap();
        assert!(!rs.contains("invoice"));
        let _ = std::fs::remove_dir_all(root);
    }

    #[test]
    fn seeders_follow_the_migrations() {
        let (root, layout) = project("seed-order");
        let migration = |v: &str| format!("fn version(&self) -> &str {{\n        \"{v}\"\n    }}");
        touch(&layout.rust.join("account/mod.rs"), "");
        touch(&layout.rust.join("account/migration.rs"), &migration("300"));
        touch(&layout.rust.join("team/mod.rs"), "");
        touch(&layout.rust.join("team/migration.rs"), &migration("100"));
        touch(&layout.rust.join("note/mod.rs"), ""); // no migration: first
        sync(&layout).unwrap();
        let rs = std::fs::read_to_string(layout.rust.join("mod.rs")).unwrap();
        let seeders = &rs[rs.find("pub fn seeders").unwrap()..];
        let order: Vec<usize> = ["note::", "team::", "account::"]
            .iter()
            .map(|m| seeders.find(m).unwrap())
            .collect();
        assert!(order.windows(2).all(|w| w[0] < w[1]), "{seeders}");
        let _ = std::fs::remove_dir_all(root);
    }

    #[test]
    fn sync_skips_halves_that_dont_exist() {
        let (root, layout) = project("none");
        assert!(sync(&layout).unwrap().is_empty());
        assert!(!layout.rust.exists() && !layout.js.exists());
        let _ = std::fs::remove_dir_all(root);
    }

    #[test]
    fn a_registry_the_user_wrote_is_never_overwritten() {
        let (root, layout) = project("owned");
        let mine = "pub mod customer; // my own\n";
        touch(&layout.rust.join("mod.rs"), mine);
        touch(&layout.rust.join("customer/mod.rs"), "");
        let err = sync(&layout).unwrap_err();
        assert!(err.contains("isn't managed by rata"), "{err}");
        assert_eq!(
            std::fs::read_to_string(layout.rust.join("mod.rs")).unwrap(),
            mine
        );
        let _ = std::fs::remove_dir_all(root);
    }

    #[test]
    fn a_folder_that_isnt_an_identifier_is_an_error() {
        let (root, layout) = project("ident");
        touch(&layout.rust.join("blog-post/mod.rs"), "");
        assert!(sync(&layout).unwrap_err().contains("snake_case"));
        let _ = std::fs::remove_dir_all(root);
    }

    #[test]
    fn wiring_hints_name_only_whats_missing() {
        let (root, layout) = project("hints");
        assert!(
            wiring_hints(&layout).is_empty(),
            "no resources, nothing to wire"
        );

        touch(&layout.rust.join("customer/mod.rs"), "");
        touch(&layout.js.join("customers/index.js"), "");
        sync(&layout).unwrap();
        touch(
            &layout.main_rs,
            "fn main() { App::new().commands(commands![greet]).run() }",
        );
        touch(&layout.routes_js, "export const routes = {};");

        let hints = wiring_hints(&layout);
        assert_eq!(hints.len(), 2, "{hints:?}");
        assert!(hints[0].contains("mod resources;"));
        assert!(hints[0].contains(".allow_abilities(resources::abilities())"));
        assert!(hints[1].contains("./resources/index.js"));

        // Partly wired: only the rest is printed.
        touch(
            &layout.main_rs,
            "mod resources;\nfn main() { App::new().commands(resources::commands()).run() }",
        );
        let hints = wiring_hints(&layout);
        assert!(!hints[0].contains("mod resources;"));
        assert!(!hints[0].contains(".commands("));
        assert!(hints[0].contains(".migrations(resources::migrations())"));

        touch(
            &layout.main_rs,
            "mod resources;\nresources::commands() resources::migrations() resources::seeders() \
             resources::abilities()",
        );
        touch(
            &layout.routes_js,
            "import { routes as r } from \"./resources/index.js\";",
        );
        assert!(wiring_hints(&layout).is_empty());
        let _ = std::fs::remove_dir_all(root);
    }
}
