//! `rata make:resource <Model> --backend /api/<plural> --generate <fields>`
//! (RFC 0005 step 5): the same resource — commands, types, events, tests, and
//! the screens — with its data on a Laravel backend instead of the local
//! database. No migration or seeder: the table is the server's.

use crate::make_resource::{Field, Format, Kind, ModelInfo, Names};

/// `model.rs`: a plain serde struct — what the API answers, not a table.
pub(crate) fn render_model(m: &ModelInfo, n: &Names, path: &str) -> String {
    let ty = &n.ty;
    let fields: String = m
        .editable
        .iter()
        .map(|f| {
            let ty = if f.nullable {
                format!("Option<{}>", f.ty)
            } else {
                f.ty.clone()
            };
            format!("    pub {}: {ty},\n", f.name)
        })
        .collect();
    format!(
        r#"//! The `{ty}` record — generated by `rata make:resource {ty} --backend {path}`,
//! and yours to change. It's what the Laravel API answers; the table is the
//! server's.

use serde::{{Deserialize, Serialize}};

#[derive(Serialize, Deserialize, specta::Type, Debug, Default, Clone, PartialEq)]
pub struct {ty} {{
    pub id: i64,
{fields}    /// ISO 8601, as Laravel sends it.
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
}}
"#
    )
}

/// `commands.rs`: Laravel's resource verbs, each one request to the API.
pub(crate) fn render_commands(m: &ModelInfo, n: &Names, abilities: bool, path: &str) -> String {
    let ty = &n.ty;
    let p = &n.plural;
    let var = &n.module;
    let human = &n.human;
    let can = |verb: &str, live: bool| {
        let live = if live { "live" } else { "" };
        match (abilities, live.is_empty()) {
            (true, true) => format!("#[command(can = \"{p}.{verb}\")]"),
            (true, false) => format!("#[command(live, can = \"{p}.{verb}\")]"),
            (false, true) => "#[command]".into(),
            (false, false) => "#[command(live)]".into(),
        }
    };
    let input_fields: String = m
        .editable
        .iter()
        .map(|f| format!("    pub {}: Option<{}>,\n", f.name, f.ty))
        .collect();
    let route = path.rsplit('/').next().unwrap_or(p);
    format!(
        r#"//! `{ty}` commands over the Laravel backend — generated by
//! `rata make:resource {ty} --backend {path}`, and yours to change.
//!
//! Laravel's resource verbs, one command each, sent to `{path}` as the
//! signed-in user. The server validates: a `422` comes back as the same
//! per-field errors a local command gives. A write here re-runs the open
//! lists (RFC 0005).{abilities_note}

use elyra::{{command, Backend, Ctx, Page, Result}};
use serde::{{Deserialize, Serialize}};

use {module}::{ty};

/// Where the Laravel API serves {p}: `Route::apiResource('{route}', …)`.
pub(super) const PATH: &str = "{path}";

/// What the list asks for: a search term, a sort and a page — passed to the
/// API as its query.
#[derive(Debug, Default, Clone, Serialize, Deserialize, specta::Type)]
#[serde(default)]
pub struct {ty}Query {{
    pub search: Option<String>,
    pub sort: Option<String>,
    /// `"asc"` (the default) or `"desc"`.
    pub direction: Option<String>,
    pub page: Option<i64>,
    pub per_page: Option<i64>,
}}

/// What a form may set. Every field is optional *here*; the server's rules say
/// what's required, and a missing one comes back as its message.
#[derive(Debug, Default, Clone, Serialize, Deserialize, specta::Type)]
pub struct {ty}Input {{
{input_fields}}}

/// Dispatched after a {human} is created. React with `App::listen`, or send it
/// to every window with `App::broadcast`.
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
pub struct {ty}Created {{
    pub {var}: {ty},
}}

/// Dispatched after a {human} is updated.
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
pub struct {ty}Updated {{
    pub {var}: {ty},
}}

/// Dispatched after a {human} is deleted.
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
pub struct {ty}Deleted {{
    pub id: i64,
}}

/// A page of {p}, searched and sorted by the server.
{can_view_live}
pub async fn {p}_index(ctx: Ctx, query: {ty}Query) -> Result<Page<{ty}>> {{
    Ok(ctx.get::<Backend>().get(PATH).query(&query).json().await?)
}}

/// One {human}.
{can_view_live}
pub async fn {p}_show(ctx: Ctx, id: i64) -> Result<{ty}> {{
    Ok(ctx
        .get::<Backend>()
        .get(format!("{{PATH}}/{{id}}"))
        .resource()
        .await?)
}}

/// Create a {human}.
{can_create}
pub async fn {p}_store(ctx: Ctx, input: {ty}Input) -> Result<{ty}> {{
    let {var}: {ty} = ctx
        .get::<Backend>()
        .post(PATH)
        .body(&input)
        .resource()
        .await?;
    ctx.dispatch({ty}Created {{
        {var}: {var}.clone(),
    }})
    .await?;
    Ok({var})
}}

/// Update a {human}.
{can_update}
pub async fn {p}_update(ctx: Ctx, id: i64, input: {ty}Input) -> Result<{ty}> {{
    let {var}: {ty} = ctx
        .get::<Backend>()
        .put(format!("{{PATH}}/{{id}}"))
        .body(&input)
        .resource()
        .await?;
    ctx.dispatch({ty}Updated {{
        {var}: {var}.clone(),
    }})
    .await?;
    Ok({var})
}}

/// Delete a {human}.
{can_delete}
pub async fn {p}_destroy(ctx: Ctx, id: i64) -> Result<()> {{
    ctx.get::<Backend>()
        .delete(format!("{{PATH}}/{{id}}"))
        .send()
        .await?;
    ctx.dispatch({ty}Deleted {{ id }}).await?;
    Ok(())
}}
"#,
        module = m.module,
        abilities_note = if abilities {
            "\n//!\n//! Every command needs an ability from `ABILITIES`, which the app must grant."
        } else {
            ""
        },
        can_view_live = can("view", true),
        can_create = can("create", false),
        can_update = can("update", false),
        can_delete = can("delete", false),
    )
}

/// A field's value in the API's JSON, for record `n`.
fn json_sample(f: &Field) -> String {
    match (f.kind, f.format) {
        (_, Format::Email) => format!("format!(\"{}{{n}}@example.com\")", f.name),
        (_, Format::Date) => "\"2026-01-01\"".into(),
        (_, Format::Reference) => "1".into(),
        (Kind::Text, _) => format!("format!(\"{} {{n}}\")", f.name),
        (Kind::Int, _) => "n".into(),
        (Kind::Float, _) => "n as f64 + 0.5".into(),
        (Kind::Bool, _) => "true".into(),
        (Kind::Other, _) => "null".into(),
    }
}

/// The input's value for a field, for input `n` (as the database tests do).
fn input_sample(f: &Field) -> String {
    match (f.kind, f.format) {
        (_, Format::Email) => format!("Some(format!(\"{}{{n}}@example.com\"))", f.name),
        (_, Format::Date) => "Some(\"2026-01-01\".to_string())".into(),
        (_, Format::Reference) => "Some(1)".into(),
        (Kind::Text, _) => format!("Some(format!(\"{} {{n}}\"))", f.name),
        (Kind::Int, _) => format!("Some(n as {})", f.ty),
        (Kind::Float, _) => format!("Some(n as {} + 0.5)", f.ty),
        (Kind::Bool, _) => "Some(true)".into(),
        (Kind::Other, _) => "Some(Default::default())".into(),
    }
}

/// `tests.rs`: the commands against an `HttpFake` standing in for Laravel.
pub(crate) fn render_tests(m: &ModelInfo, n: &Names, abilities: bool) -> String {
    let ty = &n.ty;
    let p = &n.plural;
    let human = &n.human;
    let record_fields: String = m
        .editable
        .iter()
        .map(|f| format!("        \"{}\": {},\n", f.name, json_sample(f)))
        .collect();
    let input_fields: String = m
        .editable
        .iter()
        .map(|f| format!("        {}: {},\n", f.name, input_sample(f)))
        .collect();
    let first = m
        .editable
        .first()
        .map(|f| f.name.clone())
        .unwrap_or_else(|| "name".into());
    let label = first.replace('_', " ");
    let grant = if abilities {
        "\n            .allow_abilities(ABILITIES.iter().copied())"
    } else {
        ""
    };
    let abilities_test = if abilities {
        r#"
#[test]
fn the_abilities_must_be_granted() {
    // Denied until the app grants them: a script in the window can't reach
    // the backend through these commands on its own.
    assert!(!TestApp::new(App::new()).policy().grants_ability(ABILITIES[0]));
    assert_eq!(ABILITIES.len(), 4);
}
"#
        .to_string()
    } else {
        String::new()
    };
    format!(
        r#"//! Tests for the `{ty}` resource over the backend — answered by an
//! `HttpFake` standing in for the Laravel API, so they need neither the
//! network nor the server.

use elyra::http::{{Http, HttpFake}};
use elyra::testing::TestApp;
use elyra::{{App, Backend, Dispatcher, Page}};
use serde_json::{{json, Value}};

use super::*;
use {module}::{ty};

const BASE: &str = "https://backend.test";

fn url(path: impl AsRef<str>) -> String {{
    format!("{{BASE}}{{}}", path.as_ref())
}}

fn app(fake: &HttpFake) -> TestApp {{
    TestApp::new(
        App::new()
            .backend(Backend::new(BASE))
            .swap(Http::fake(fake.clone()))
            .swap(Dispatcher::fake())
            .commands(commands()){grant},
    )
}}

/// A {human} as the API answers it.
fn record(n: i64) -> Value {{
    json!({{
        "id": n,
{record_fields}        "created_at": "2026-01-01T00:00:00.000000Z",
        "updated_at": "2026-01-01T00:00:00.000000Z",
    }})
}}

/// A valid input; `n` makes each one distinct.
fn input(n: u32) -> {ty}Input {{
    {ty}Input {{
{input_fields}    }}
}}

#[tokio::test]
async fn the_list_and_a_record_come_from_the_api() {{
    let fake = HttpFake::new()
        .get(
            url(super::commands::PATH),
            200,
            json!({{ "data": [record(1), record(2)], "current_page": 2, "per_page": 2,
                    "total": 4, "last_page": 2 }}),
        )
        // An API Resource wraps a record in `data`; a model returned as-is
        // doesn't. Either reads.
        .get(url(format!("{{}}/1", super::commands::PATH)), 200, json!({{ "data": record(1) }}));
    let app = app(&fake);

    let page: Page<{ty}> = app
        .invoke_ok(
            "{p}_index",
            ({ty}Query {{
                search: Some("x".into()),
                page: Some(2),
                ..Default::default()
            }},),
        )
        .await;
    assert_eq!((page.data.len(), page.total, page.current_page), (2, 4, 2));
    let sent = fake.assert_sent("GET", &url(super::commands::PATH));
    assert!(sent.url.contains("search=x") && sent.url.contains("page=2"), "{{}}", sent.url);

    let shown: {ty} = app.invoke_ok("{p}_show", (1,)).await;
    assert_eq!(shown.id, 1);
}}

#[tokio::test]
async fn writes_go_to_the_api_and_dispatch_their_events() {{
    let one = url(format!("{{}}/1", super::commands::PATH));
    let fake = HttpFake::new()
        .post(url(super::commands::PATH), 201, json!({{ "data": record(1) }}))
        .put(one.clone(), 200, record(1))
        .delete(one.clone(), 204, Value::Null);
    let app = app(&fake);

    let created: {ty} = app.invoke_ok("{p}_store", (input(1),)).await;
    assert_eq!(created.id, 1);
    let sent = fake.assert_sent("POST", &url(super::commands::PATH));
    assert!(sent.body.unwrap()["{first}"] != Value::Null);

    app.invoke_ok::<{ty}>("{p}_update", (1, input(2))).await;
    fake.assert_sent("PUT", &one);
    app.invoke_ok::<()>("{p}_destroy", (1,)).await;
    fake.assert_sent("DELETE", &one);

    let events = app.get::<Dispatcher>();
    events.assert_dispatched::<{ty}Created>();
    events.assert_dispatched::<{ty}Updated>();
    events.assert_dispatched_with(|e: &{ty}Deleted| e.id == 1);
}}

#[tokio::test]
async fn the_servers_validation_comes_back_per_field() {{
    let fake = HttpFake::new().post(
        url(super::commands::PATH),
        422,
        json!({{ "message": "The {label} field is required.",
                "errors": {{ "{first}": ["The {label} field is required."] }} }}),
    );
    let errors = app(&fake)
        .invoke_validation_errors("{p}_store", ({ty}Input::default(),))
        .await
        .expect("the server's validation bag");
    assert_eq!(errors["{first}"], ["The {label} field is required."]);
}}

#[tokio::test]
async fn a_missing_{var}_is_not_found() {{
    let fake = HttpFake::new().get(url(format!("{{}}/99", super::commands::PATH)), 404, json!({{}}));
    let missing = app(&fake).invoke_err("{p}_show", (99,)).await;
    assert!(missing.contains("not found"), "{{missing}}");
}}
{abilities_test}"#,
        module = m.module,
        var = n.module,
    )
}
