<script>
  import { onMount } from "svelte";
  import {
    channel,
    openAbout,
    checkForUpdate,
    dialog,
    shell,
    clipboard,
    notify,
    confirm,
    toast,
    contextMenu,
    registerCommands,
    appWindow,
    onFileDrop,
    onShortcut,
    onMenu,
    store,
  } from "@elyra/runtime";

  let dropped = $state([]);
  onFileDrop((paths) => {
    dropped = paths;
    toast(`Dropped ${paths.length} file(s)`, { variant: "success" });
  });
  onShortcut((accel) => toast(`Shortcut: ${accel}`));
  onMenu((id) => toast(`Menu: ${id}`));
  // Restore the last-saved name from the settings store.
  store.get("name").then((n) => {
    if (typeof n === "string") name = n;
  });
  const saveName = () => store.set("name", name).then(() => toast("Saved", { variant: "success" }));

  async function askDelete() {
    if (await confirm("Delete this item? This cannot be undone.", { danger: true, confirmLabel: "Delete" })) {
      toast("Deleted", { variant: "success" });
    }
  }
  function headerMenu(e) {
    contextMenu(e, [
      { label: "About", action: () => openAbout() },
      { label: "Check for updates", action: () => checkUpdates() },
      { separator: true },
      { label: "Copy greeting", action: () => clipboard.writeText("Hello from Elyra") },
    ]);
  }
  registerCommands([
    { id: "greet", title: "Greet", subtitle: "Run the greet command", action: () => doGreet() },
    { id: "about", title: "About this app", action: () => openAbout() },
    { id: "update", title: "Check for updates", action: () => checkUpdates() },
    { id: "notify", title: "Send a notification", action: () => ping() },
  ]);

  let picked = $state("");
  async function pickFile() {
    const paths = await dialog.open({ title: "Pick a file" });
    picked = paths[0] ?? "(cancelled)";
  }
  const openRepo = () => shell.openExternal("https://github.com/kwhorne/elyra-framework");
  const copyHi = () => clipboard.writeText("Hello from Elyra");
  const ping = () => notify("Elyra", "Native notification from the example app.");

  async function checkUpdates() {
    try {
      const r = await checkForUpdate();
      if (!r.available)
        alert(r.error ? `Update check failed: ${r.error}` : "You're on the latest version.");
    } catch (e) {
      alert(String(e.message ?? e));
    }
  }
  import { api } from "./bindings"; // generated by `rata codegen`

  // --- M0: commands -------------------------------------------------------
  let name = $state("World");
  let greeting = $state("");
  let greetErr = $state("");
  let a = $state(2);
  let b = $state(3);
  let sum = $state(null);
  let info = $state(null);

  async function doGreet() {
    greetErr = "";
    try {
      greeting = await api.greet(name);
    } catch (e) {
      greetErr = String(e.message ?? e);
    }
  }
  const doAdd = async () => (sum = await api.add(Number(a), Number(b)));
  const loadInfo = async () => (info = await api.system_info());

  // Database-backed todos (Result commands over the Database service).
  let todos = $state([]);
  let newTodo = $state("");
  let todoErr = $state("");
  async function loadTodos() {
    todoErr = "";
    try {
      todos = await api.list_todos();
    } catch (e) {
      todoErr = String(e.message ?? e);
    }
  }
  async function addTodo() {
    if (!newTodo.trim()) return;
    await api.add_todo(newTodo);
    newTodo = "";
    await loadTodos();
  }

  // Tray menu clicks arrive on the "tray" channel; show the latest.
  let lastTray = $state("—");
  channel("tray").subscribe((id) => {
    if (id !== undefined) lastTray = id;
  });

  // Updater target/version (demo of the updater module being wired in).
  let target = $state("—");
  const loadTarget = async () => (target = await api.update_target());

  // A Result command: Err rejects the promise as a CommandError.
  let divOut = $state("—");
  async function doDiv() {
    try {
      divOut = String(await api.checked_div(Number(a), Number(b)));
    } catch (e) {
      divOut = "error: " + String(e.message ?? e);
    }
  }

  // --- M1: event-bus latency probe ---------------------------------------
  let samples = $state(0);
  let latency = $state(null);
  const pending = new Map();
  let seq = 0;

  channel("echo").subscribe((n) => {
    if (n === undefined) return;
    const sentAt = pending.get(n);
    if (sentAt === undefined) return;
    pending.delete(n);
    times.push(performance.now() - sentAt);
    if (pending.size === 0) report();
  });

  let times = [];
  function report() {
    const sorted = [...times].sort((x, y) => x - y);
    const pct = (p) => sorted[Math.min(sorted.length - 1, Math.floor(p * sorted.length))];
    latency = {
      n: sorted.length,
      avg: +(sorted.reduce((s, x) => s + x, 0) / sorted.length).toFixed(3),
      p50: +pct(0.5).toFixed(3),
      p95: +pct(0.95).toFixed(3),
      max: +sorted[sorted.length - 1].toFixed(3),
    };
  }

  async function measureLatency() {
    times = [];
    latency = null;
    const N = 200;
    for (let i = 0; i < N; i++) {
      const s = seq++;
      pending.set(s, performance.now());
      api.emit_echo(s); // fire-and-forget; the echo returns via the bus
    }
    samples += N;
  }

  // --- M1: burst batching -------------------------------------------------
  let burstCount = $state(0);
  let burstMs = $state(null);
  channel("burst").subscribe((n) => {
    if (n === undefined) return;
    burstCount += 1;
  });
  async function doBurst() {
    burstCount = 0;
    const t0 = performance.now();
    const total = await api.burst(1000);
    // Events arrive over the next frames; sample after a tick.
    setTimeout(() => (burstMs = +(performance.now() - t0).toFixed(1)), 50);
    void total;
  }

  // --- M1: live stream via the channel store ------------------------------
  const stream = channel("stream"); // usable as `$stream`
  const startStream = () => api.stream(100, 16);

  // --- Opt-in input->paint benchmark (ELYRA_BENCH=1) ----------------------
  onMount(async () => {
    let enabled = false;
    try {
      enabled = await api.bench_enabled();
    } catch {}
    if (enabled) runBench();
  });

  async function runBench() {
    const N = 300;
    const sent = new Map();
    const paints = [];
    let done = 0;
    const unsub = channel("bench").subscribe((n) => {
      if (n === undefined) return;
      const t = sent.get(n);
      if (t === undefined) return;
      sent.delete(n);
      // Include the paint frame: measure to the next animation frame.
      requestAnimationFrame(() => {
        paints.push(performance.now() - t);
        if (++done === N) finish();
      });
    });
    async function finish() {
      unsub();
      const s = paints.sort((x, y) => x - y);
      const pct = (p) => s[Math.min(s.length - 1, Math.floor(p * s.length))];
      await api.bench_report({
        n: s.length,
        avg: +(s.reduce((a, x) => a + x, 0) / s.length).toFixed(3),
        p50: +pct(0.5).toFixed(3),
        p95: +pct(0.95).toFixed(3),
        max: +s[s.length - 1].toFixed(3),
      });
    }
    for (let i = 0; i < N; i++) {
      sent.set(i, performance.now());
      await api.bench_echo(i);
    }
  }
</script>

<main>
  <header>
    <h1>Elyra <span class="badge">M1 · EventBus</span></h1>
    <p>Runes frontend over MessagePack, with server-pushed events (long-poll).</p>
    <button onclick={() => openAbout()}>About this app</button>
    <button onclick={checkUpdates}>Check for updates</button>
    <button onclick={pickFile}>Pick file</button>
    <button onclick={openRepo}>Open repo</button>
    <button onclick={copyHi}>Copy</button>
    <button onclick={ping}>Notify</button>
    <button onclick={saveName}>Save name</button>
    <button onclick={askDelete}>Delete (confirm)</button>
    <button onclick={() => appWindow.minimize()}>Minimize</button>
    <button onclick={() => appWindow.toggleMaximize()}>Maximize</button>
    <button onclick={() => appWindow.toggleFullscreen()}>Fullscreen</button>
    <p class="muted" oncontextmenu={headerMenu}>Right-click here for a context menu · press ⌘K · drop files onto the window</p>
    {#if picked}<p class="muted">Picked: {picked}</p>{/if}
    {#if dropped.length}<p class="muted">Dropped: {dropped.join(", ")}</p>{/if}
  </header>

  <section>
    <h2>greet(name)</h2>
    <div class="row">
      <input bind:value={name} placeholder="name" />
      <button onclick={doGreet}>invoke</button>
    </div>
    <output class:error={greetErr}>{greetErr || greeting || "—"}</output>
  </section>

  <section>
    <h2>add(a, b)</h2>
    <div class="row">
      <input type="number" bind:value={a} />
      <input type="number" bind:value={b} />
      <button onclick={doAdd}>invoke</button>
    </div>
    <output>{sum ?? "—"}</output>
  </section>

  <section>
    <h2>checked_div(a, b) — Result</h2>
    <div class="row"><button onclick={doDiv}>invoke (uses a, b above)</button></div>
    <output class:error={divOut.startsWith("error")}>{divOut}</output>
  </section>

  <section class="m1">
    <h2>todos — sqlite via Database service</h2>
    <div class="row">
      <input bind:value={newTodo} placeholder="new todo" onkeydown={(e) => e.key === "Enter" && addTodo()} />
      <button onclick={addTodo}>add</button>
      <button onclick={loadTodos}>load</button>
    </div>
    <output class:error={todoErr}>{todoErr || (todos.length ? todos.map((t) => `#${t.id} ${t.title}`).join("\n") : "—")}</output>
  </section>

  <section class="m1">
    <h2>system tray + updater</h2>
    <div class="row"><button onclick={loadTarget}>update_target()</button></div>
    <output>target: {target}
last tray click: {lastTray}  (use the menubar icon → “Open Elyra”)</output>
  </section>

  <section>
    <h2>open_window() — multi-window</h2>
    <div class="row"><button onclick={() => api.open_window()}>open second window</button></div>
    <output>opens a native window sharing this app's commands + event bus</output>
  </section>

  <section>
    <h2>system_info()</h2>
    <div class="row"><button onclick={loadInfo}>invoke</button></div>
    <output>{info ? JSON.stringify(info, null, 2) : "—"}</output>
  </section>

  <section class="m1">
    <h2>event round-trip latency (200×)</h2>
    <div class="row"><button onclick={measureLatency}>measure</button></div>
    <output>{latency ? JSON.stringify(latency) + " ms" : "—"}</output>
  </section>

  <section class="m1">
    <h2>burst → batched events (1000×)</h2>
    <div class="row"><button onclick={doBurst}>burst</button></div>
    <output>received {burstCount} events{burstMs !== null ? ` in ${burstMs} ms` : ""}</output>
  </section>

  <section class="m1">
    <h2>live stream (channel store)</h2>
    <div class="row"><button onclick={startStream}>start</button></div>
    <output>$stream = {$stream ?? "—"}</output>
  </section>
</main>

<style>
  :global(body) {
    margin: 0;
    background: radial-gradient(120% 120% at 50% 0%, #17203a 0%, #0b0f1a 60%);
    color: #e7ecf5;
    font: 15px/1.5 ui-sans-serif, system-ui, sans-serif;
  }
  main { max-width: 520px; margin: 0 auto; padding: 2rem 1.5rem; }
  h1 { font-size: 1.35rem; margin: 0 0 0.25rem; }
  .badge {
    font-size: 0.7rem; background: #1e6f4c; color: #c6ffe4;
    padding: 0.15rem 0.5rem; border-radius: 999px; vertical-align: middle;
  }
  header p { color: #8b97ad; margin: 0 0 1.5rem; }
  section { margin-top: 1.25rem; }
  section.m1 { padding-top: 1.1rem; border-top: 1px solid rgba(255, 255, 255, 0.07); }
  h2 {
    font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.08em;
    color: #8b97ad; margin: 0 0 0.5rem;
  }
  .row { display: flex; gap: 0.5rem; }
  input {
    flex: 1; min-width: 0; background: #0d1424;
    border: 1px solid rgba(255, 255, 255, 0.12); color: #e7ecf5;
    border-radius: 8px; padding: 0.5rem 0.7rem; font: inherit;
  }
  button {
    background: #3b82f6; border: 0; color: #fff; font: inherit; font-weight: 600;
    padding: 0.5rem 0.9rem; border-radius: 8px; cursor: pointer;
  }
  button:hover { background: #2f6fe0; }
  output {
    display: block; margin-top: 0.35rem; padding: 0.6rem 0.7rem; background: #0d1424;
    border: 1px dashed rgba(255, 255, 255, 0.12); border-radius: 8px;
    font-family: ui-monospace, monospace; font-size: 0.85rem; color: #7ee0a3;
    white-space: pre-wrap; word-break: break-word;
  }
  output.error { color: #ff8080; }
</style>
