// Generated by Ratatosk (`rata codegen`). Do not edit by hand.


import { invoke } from "@elyra/runtime";

export type BenchStats = {
	n: number,
	avg: number,
	p50: number,
	p95: number,
	max: number,
};

/**  A struct result — serialized as a named map, decoded to a plain JS object. */
export type SystemInfo = {
	os: string,
	arch: string,
	commands: string[],
};

/**  A database model — CRUD + query builder come from `#[derive(Model)]`. */
export type Todo = {
	id: number,
	title: string,
	done: boolean,
};

export const api = {
  add(a: number, b: number): Promise<number> {
    return invoke("add", a, b);
  },
  add_todo(title: string): Promise<Todo> {
    return invoke("add_todo", title);
  },
  bench_echo(seq: number): Promise<number> {
    return invoke("bench_echo", seq);
  },
  bench_enabled(): Promise<boolean> {
    return invoke("bench_enabled");
  },
  bench_report(stats: BenchStats): Promise<null> {
    return invoke("bench_report", stats);
  },
  burst(count: number): Promise<number> {
    return invoke("burst", count);
  },
  checked_div(a: number, b: number): Promise<number> {
    return invoke("checked_div", a, b);
  },
  emit_echo(seq: number): Promise<number> {
    return invoke("emit_echo", seq);
  },
  greet(name: string): Promise<string> {
    return invoke("greet", name);
  },
  list_todos(): Promise<Todo[]> {
    return invoke("list_todos");
  },
  open_window(): Promise<null> {
    return invoke("open_window");
  },
  stream(count: number, interval_ms: number): Promise<number> {
    return invoke("stream", count, interval_ms);
  },
  system_info(): Promise<SystemInfo> {
    return invoke("system_info");
  },
  update_target(): Promise<string> {
    return invoke("update_target");
  },
};

